table=[
"48 48 161 2 ",
"   c None",
".  c #040404",
"X  c #090909",
"o  c gray5",
"O  c #0E0E0E",
"+  c gray7",
"@  c gray8",
"#  c #161616",
"$  c #1B1B1B",
"%  c #1D1D1D",
"&  c #202020",
"*  c gray13",
"=  c #232323",
"-  c #252525",
";  c #272727",
":  c gray16",
">  c #2A2A2A",
",  c #2D2D2D",
"<  c gray19",
"1  c #323232",
"2  c #343434",
"3  c #353535",
"4  c #373737",
"5  c #393939",
"6  c gray23",
"7  c gray24",
"8  c #3E3E3E",
"9  c gray25",
"0  c gray26",
"q  c #444444",
"w  c gray27",
"e  c #464646",
"r  c gray28",
"t  c #484848",
"y  c gray29",
"u  c #4B4B4B",
"i  c #4C4C4C",
"p  c gray30",
"a  c #4E4E4E",
"s  c gray31",
"d  c #505050",
"f  c #515151",
"g  c gray32",
"h  c #535353",
"j  c gray33",
"k  c #555555",
"l  c #565656",
"z  c gray34",
"x  c #585858",
"c  c gray35",
"v  c #5A5A5A",
"b  c #5B5B5B",
"n  c gray36",
"m  c #5D5D5D",
"M  c gray37",
"N  c #5F5F5F",
"B  c #606060",
"V  c gray38",
"C  c #626262",
"Z  c gray39",
"A  c #646464",
"S  c #656565",
"D  c gray40",
"F  c #686868",
"G  c DimGray",
"H  c #6A6A6A",
"J  c gray42",
"K  c #6D6D6D",
"L  c gray43",
"P  c #6F6F6F",
"I  c gray44",
"U  c #717171",
"Y  c #727272",
"T  c gray45",
"R  c #747474",
"E  c gray46",
"W  c #767676",
"Q  c #777777",
"!  c gray47",
"~  c #797979",
"^  c gray48",
"/  c #7B7B7B",
"(  c #7C7C7C",
")  c gray49",
"_  c #7E7E7E",
"`  c gray50",
"'  c #808080",
"]  c #818181",
"[  c #838383",
"{  c gray52",
"}  c #868686",
"|  c #888888",
" . c #898989",
".. c gray54",
"X. c gray55",
"o. c #909090",
"O. c #929292",
"+. c #979797",
"@. c #9A9A9A",
"#. c #9D9D9D",
"$. c gray62",
"%. c #AAAAAA",
"&. c gray68",
"*. c gray69",
"=. c gray70",
"-. c gray71",
";. c gray72",
":. c #B9B9B9",
">. c #BBBBBB",
",. c gray",
"<. c #C0C0C0",
"1. c #C5C5C5",
"2. c #C8C8C8",
"3. c gray79",
"4. c #CACACA",
"5. c #CBCBCB",
"6. c gray80",
"7. c #CECECE",
"8. c gray81",
"9. c gray82",
"0. c LightGray",
"q. c gray83",
"w. c #D5D5D5",
"e. c gray84",
"r. c #D7D7D7",
"t. c gray85",
"y. c #DADADA",
"u. c gainsboro",
"i. c #DDDDDD",
"p. c gray87",
"a. c #DFDFDF",
"s. c gray88",
"d. c #E1E1E1",
"f. c #E2E2E2",
"g. c gray89",
"h. c #E4E4E4",
"j. c gray90",
"k. c #E6E6E6",
"l. c #E7E7E7",
"z. c gray91",
"x. c #EAEAEA",
"c. c gray92",
"v. c #ECECEC",
"b. c gray93",
"n. c #EEEEEE",
"m. c #EFEFEF",
"M. c gray94",
"N. c gray95",
"B. c #F3F3F3",
"V. c #F4F4F4",
"C. c gray96",
"Z. c #F6F6F6",
"A. c gray97",
"S. c #F8F8F8",
"D. c #F9F9F9",
"F. c gray98",
"G. c #FBFBFB",
"H. c gray99",
"J. c #FDFDFD",
"K. c #FEFEFE",
"L. c white",
"                                      } } } } } } } } } }                                       ",
"                                ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ]                                 ",
"                          ] ] ] ] ( ( ( ~ ~ ~ Q Q ~ ~ ~ ( ( ( ] ] ] ]                           ",
"                        ] ( ( ~ ~ Q U L J J A A A A J J L U Q ~ ~ ( ( ]                         ",
"                    ( ( ( ~ Q U J A n n J Q ] } } ] Q J n n A J U Q ~ ( ( (                     ",
"                  ( ~ ~ Q L A V n ~ #.:.1.5.5.5.5.5.5.1.:.#.~ n V J L Q ~ ~ (                   ",
"                ~ ~ Q U J n n ..:.5.8.e.a.s.s.s.s.s.a.y.e.8.5.:...n n J U Q ~ ~                 ",
"              Q Q U L A c ( :.5.e.s.k.x.x.x.x.x.x.x.x.k.s.s.y.0.5.:.( c A L U Q Q               ",
"            Q Q U J V n #.5.e.k.x.x.m.m.M.M.M.M.M.M.m.m.x.x.k.s.y.0.5.#.n V J U Q Q             ",
"          Q U U J n V *.8.a.x.m.m.M.M.Z.Z.Z.Z.Z.Z.Z.Z.M.M.m.m.x.k.a.e.8.*.V n J U U Q           ",
"        Q U U J n n -.8.k.m.m.M.M.Z.Z.D.D.D.D.D.D.D.D.D.Z.Z.M.m.x.k.s.y.8.-.n n J U U Q         ",
"        U L J n c *.8.k.m.M.M.Z.Z.D.D.D.J.J.J.J.J.J.J.D.D.D.Z.Z.M.m.k.s.y.8.*.c n J L U         ",
"      U L J V j #.8.k.m.M.Z.Z.D.D.J.-.M.J.J.J.J.J.J.J.J.J.J.D.D.Z.M.m.x.s.y.8.#.j V J L U       ",
"    L L J A j ~ 5.s.m.M.Z.Z.D.D.J.J.o.+.e.J.J.J.J.J.J.J.J.J.J.D.D.Z.M.m.k.s.e.5.~ j A J L L     ",
"    L J J n j :.e.m.M.Z.Z.D.D.J.J.J.o...] %.M.J.J.J.J.J.J.J.J.J.J.D.Z.M.m.k.a.0.:.j n J J L     ",
"    J J V j } 5.k.m.M.Z.D.D.J.J.J.J...] ( ~ ] 8.J.J.J.J.J.J.J.J.J.J.D.Z.M.x.s.y.5.} j V J J     ",
"  J J A c d :.y.m.M.Z.D.J.J.J.J.J.J.} ( Q U L J @.M.J.J.J.J.J.J.J.J.D.D.M.m.k.a.0.:.d c A J J   ",
"  J A V j U 5.k.M.Z.Z.D.J.J.J.J.J.J.] ~ U J A V n L 5.J.J.J.J.J.J.J.J.D.Z.M.x.s.y.5.U j V A J   ",
"  J A n a @.0.m.M.Z.D.D.J.J.J.J.J.J.~ U J A n c c j c o.M.J.J.J.J.J.J.J.D.M.m.k.a.8.@.a n A J   ",
"A A V c a :.e.k.M.Z.D.J.J.J.J.J.J.J.Q L A n c d d d d d A 1.J.J.J.J.J.J.D.Z.M.x.s.e.:.a c V A A ",
"A A n j c 1.e.s.m.Z.D.J.J.J.J.J.J.J.U J V c d a t t t a d j o.M.J.J.J.J.D.Z.M.x.s.e.1.c j n A A ",
"A V n d J 5.y.k.m.M.D.J.J.J.J.J.J.J.L A c d t q 0 q q t a j c L 5.J.J.J.D.D.M.m.k.y.5.J d n V A ",
"V V c a Q 5.y.k.m.Z.D.J.J.J.J.J.J.J.J V j a q 8 8 0 0 q t d j n V @.M.J.J.D.Z.m.k.y.5.Q a c V V ",
"V V c a ( 5.a.k.m.Z.D.J.J.J.J.J.J.J.d a t q 6 3 3 6 6 8 0 q a j n A U 5.J.D.Z.m.k.a.5.( a c V V ",
"V n c a ( 5.a.k.m.Z.D.J.J.J.J.J.J.J.1 - $ + X . O # = > 3 8 t d n A U 5.J.D.Z.m.k.a.5.( a c n V ",
"V n c a Q 5.y.k.m.Z.D.J.J.J.J.J.J.J.1 - % # O X O # = > 3 8 t d n +.M.J.J.D.Z.m.k.y.5.Q a c n V ",
"n n c a J 5.y.k.m.M.D.J.J.J.J.J.J.J.1 > = $ # + # $ = , 3 0 t V 5.J.J.J.J.D.M.m.k.y.5.J a c n n ",
"n n c a j 1.e.s.x.M.Z.D.J.J.J.J.J.J.3 1 - = % $ % = > 1 6 q ..M.J.J.J.J.D.Z.M.x.s.e.1.j a c n n ",
"n n c d q :.e.s.x.M.Z.D.J.J.J.J.J.J.6 3 , - - - - > 1 6 d ,.J.J.J.J.J.J.D.Z.M.x.s.e.:.q d c n n ",
"  n c d q +.8.a.k.m.M.D.J.J.J.J.J.J.0 6 3 1 , , , 1 3 ( m.J.J.J.J.J.J.J.D.M.m.k.a.8.+.q d c n   ",
"  c c j t J 5.y.s.x.M.Z.D.J.J.J.J.J.t 0 8 6 3 3 3 a ,.J.J.J.J.J.J.J.J.D.Z.M.x.s.y.5.J t j c c   ",
"  c c j a q :.0.a.k.m.M.D.D.J.J.J.J.a t q 0 0 0 ] m.J.J.J.J.J.J.J.J.D.D.M.m.k.a.0.:.q a j c c   ",
"    c j d q ] 5.y.s.x.M.Z.D.J.J.J.J.j d a t c <.J.J.J.J.J.J.J.J.J.J.D.Z.M.x.s.y.5.] q d j c     ",
"    c j d t t :.0.a.k.m.M.Z.D.J.J.J.n c j X.m.J.J.J.J.J.J.J.J.J.J.D.Z.M.m.k.a.0.:.t t d j c     ",
"    c j j a q L 5.e.s.k.m.M.Z.D.D.J.A U 5.J.J.J.J.J.J.J.J.J.J.D.D.Z.M.m.k.s.e.5.L q a j j c     ",
"      c j d t 0 +.8.y.s.x.m.M.Z.D.D.+.m.J.J.J.J.J.J.J.J.J.J.D.D.Z.M.m.x.s.y.8.+.0 t d j c       ",
"        j j d t q &.8.y.s.k.m.M.M.Z.D.D.D.J.J.J.J.J.J.D.D.D.Z.M.M.m.k.s.y.8.&.q t d j j         ",
"        j j d a q a *.8.y.s.k.x.m.M.M.Z.Z.D.D.D.D.D.D.Z.Z.M.M.m.x.k.s.y.8.*.a q a d j j         ",
"          j j d a q a &.8.e.a.s.k.x.m.M.M.M.Z.Z.Z.Z.M.M.M.m.x.k.s.a.e.8.&.a q a d j j           ",
"            j j d a q q +.5.0.y.a.s.k.x.x.m.m.m.m.m.m.x.x.k.s.a.y.0.5.+.q q a d j j             ",
"              j j d a q 0 L :.5.0.y.a.s.s.k.k.k.k.k.k.s.s.a.y.e.5.:.L 0 q a d j j               ",
"                j j d a t 0 q ( :.5.8.e.e.y.y.a.a.y.y.e.e.8.5.,.( q 0 t a d j j                 ",
"                  j j d d a t 0 0 J +.:.1.5.5.5.5.5.5.1.:.+.J 0 0 t a d d j j                   ",
"                    j j d d a a t q 0 0 d V U ~ ~ U A d 0 0 q t a a d d j j                     ",
"                        j j d d d a t t t q q 0 0 q q q t t a d d d j j                         ",
"                          d j j d d d d d a a a a a a a d d d d j j d                           ",
"                                j d d j d d d d d d d d d d d j                                 ",
"                                      j j j d d d d d d d                                       "
]
