table=[
"48 48 158 2 ",
"   c None",
".  c #060606",
"X  c gray5",
"o  c #0E0E0E",
"O  c gray7",
"+  c #151515",
"@  c #181818",
"#  c #1D1D1D",
"$  c gray12",
"%  c #202020",
"&  c gray14",
"*  c gray15",
"=  c #282828",
"-  c #2A2A2A",
";  c #2D2D2D",
":  c gray19",
">  c #313131",
",  c #323232",
"<  c #353535",
"1  c #373737",
"2  c #393939",
"3  c gray23",
"4  c #3C3C3C",
"5  c gray24",
"6  c #3E3E3E",
"7  c #3F3F3F",
"8  c #414141",
"9  c gray26",
"0  c #444444",
"q  c gray27",
"w  c #464646",
"e  c gray28",
"r  c #484848",
"t  c #494949",
"y  c gray29",
"u  c #4B4B4B",
"i  c gray30",
"p  c #4E4E4E",
"a  c gray31",
"s  c #505050",
"d  c #515151",
"f  c gray32",
"g  c #535353",
"h  c gray33",
"j  c #555555",
"k  c #565656",
"l  c gray34",
"z  c #585858",
"x  c gray35",
"c  c #5A5A5A",
"v  c #5B5B5B",
"b  c gray36",
"n  c #5D5D5D",
"m  c gray37",
"M  c #5F5F5F",
"N  c #606060",
"B  c gray38",
"V  c #626262",
"C  c gray39",
"Z  c #646464",
"A  c #656565",
"S  c gray40",
"D  c #676767",
"F  c #686868",
"G  c DimGray",
"H  c #6A6A6A",
"J  c gray42",
"K  c #6C6C6C",
"L  c #6D6D6D",
"P  c gray43",
"I  c #6F6F6F",
"U  c gray44",
"Y  c #717171",
"T  c #727272",
"R  c gray45",
"E  c #747474",
"W  c gray46",
"Q  c #767676",
"!  c #777777",
"~  c gray47",
"^  c #797979",
"/  c gray48",
"(  c #7B7B7B",
")  c #7C7C7C",
"_  c gray49",
"`  c #7E7E7E",
"'  c gray50",
"]  c #808080",
"[  c #818181",
"{  c gray51",
"}  c #838383",
"|  c gray52",
" . c #868686",
".. c #898989",
"X. c gray54",
"o. c gray55",
"O. c #8E8E8E",
"+. c gray57",
"@. c #959595",
"#. c gray59",
"$. c #979797",
"%. c gray60",
"&. c #9A9A9A",
"*. c #9D9D9D",
"=. c gray68",
"-. c gray69",
";. c #B4B4B4",
":. c gray72",
">. c #B9B9B9",
",. c gray73",
"<. c #BBBBBB",
"1. c #C5C5C5",
"2. c #C8C8C8",
"3. c gray79",
"4. c #CBCBCB",
"5. c gray80",
"6. c #CECECE",
"7. c gray81",
"8. c gray82",
"9. c LightGray",
"0. c gray83",
"q. c #D5D5D5",
"w. c gray84",
"e. c #D7D7D7",
"r. c gray85",
"t. c gray86",
"y. c gainsboro",
"u. c gray87",
"i. c #DFDFDF",
"p. c gray88",
"a. c #E1E1E1",
"s. c #E2E2E2",
"d. c #E4E4E4",
"f. c gray90",
"g. c #E6E6E6",
"h. c #E7E7E7",
"j. c gray91",
"k. c #EAEAEA",
"l. c gray92",
"z. c #ECECEC",
"x. c gray93",
"c. c #EEEEEE",
"v. c #EFEFEF",
"b. c gray94",
"n. c #F1F1F1",
"m. c gray95",
"M. c #F4F4F4",
"N. c gray96",
"B. c #F6F6F6",
"V. c gray97",
"C. c #F8F8F8",
"Z. c #F9F9F9",
"A. c gray98",
"S. c #FBFBFB",
"D. c gray99",
"F. c #FDFDFD",
"G. c #FEFEFE",
"H. c white",
"                                       . . . . . . . . . .                                      ",
"                                [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [                                 ",
"                          [ [ [ [ ) ) ) ~ ~ ~ E E ~ ~ ~ ) ) ) [ [ [ [                           ",
"                        ) ) ) ~ ~ E Y P G G Z Z Z Z G G P Y E ~ ~ ) ) [                         ",
"                    ) ) ) ~ E Y G Z b b G E [  . .[ E G b b Z G Y E ~ ) ) )                     ",
"                  ) ~ ~ E P Z B b ~ *.>.1.4.4.4.4.4.4.1.>.*.~ b B G P E ~ ~ )                   ",
"                ~ ~ E Y G b b ..>.4.7.w.i.p.p.p.p.p.i.t.w.7.4.>...b b G Y E ~ ~                 ",
"              ~ E Y P Z x ) >.4.w.p.g.k.k.k.k.k.k.k.k.g.p.p.t.9.4.>.) x Z P Y E ~               ",
"            E E Y G B b *.4.w.g.k.k.v.v.b.b.b.b.b.b.v.v.k.k.g.p.t.9.4.*.b B G Y E E             ",
"          E Y Y G b B -.7.i.k.v.v.b.b.B.B.B.B.B.B.B.B.b.b.v.v.k.g.i.w.7.-.B b G Y Y E           ",
"        E Y Y G b b ;.7.g.v.v.b.B.B.B.Z.Z.Z.Z.Z.Z.Z.Z.Z.B.B.b.v.k.g.p.t.7.;.b b G Y Y E         ",
"        Y P G b x -.7.g.v.b.B.B.B.Z.Z.Z.F.F.F.F.F.F.F.Z.Z.Z.B.B.b.v.g.p.t.7.-.x b G P Y         ",
"      Y P G B h *.7.g.v.b.B.B.Z.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.Z.B.b.v.k.p.t.7.*.h B G P Y       ",
"    P P G Z h ~ 4.p.v.b.B.B.Z.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.Z.B.b.v.g.p.w.4.~ h Z G P P     ",
"    P P Z b h >.w.v.b.B.B.Z.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.B.b.v.g.i.9.>.h b Z P P     ",
"    P G B h  .4.g.v.b.B.Z.Z.F.%.#.+... .[ ) ~ ~ E E E E E ~ ~ ) ) F.Z.B.b.k.p.t.4. .h B G P     ",
"  G G Z b f >.t.v.b.B.Z.Z.F.F.#.+...[ ) E Y G Z Z B B b b B B Z Z F.Z.Z.B.v.g.i.9.>.f b Z G G   ",
"  G Z B h Y 4.g.b.B.B.Z.F.F.F.#.o. .) E Y G Z B b x x x x x b b B F.F.Z.B.b.k.p.t.4.Y h B Z G   ",
"  Z Z b p %.9.v.b.B.Z.Z.F.F.F.+...[ ~ Y G B b x h f f f f h h x b F.F.F.Z.B.v.g.i.7.%.p b Z Z   ",
"Z Z B x p >.w.g.b.B.Z.F.F.F.F.+. .) Y P Z b h f p r r r p p f h x F.F.F.Z.B.b.k.p.w.>.p x B Z Z ",
"Z Z b h x 1.w.p.v.B.Z.F.F.F.F.o.[ ~ Y Z b h f r q q q q q r r f h F.F.F.Z.B.b.k.p.w.1.x h b Z Z ",
"Z B b f G 4.t.g.v.b.Z.F.F.F.F.o.) E P Z x f r q 5 5 5 5 9 q r p f F.F.F.Z.Z.b.v.g.t.4.G f b B Z ",
"B B b p E 4.t.g.v.B.Z.F.F.F.F. .) E G B h p q 5 < < 2 2 5 9 q r p F.F.F.F.Z.B.v.g.t.4.E p b B B ",
"B B x p ) 4.i.g.v.B.Z.F.F.F.F.f r r p p r q 5 < , , , , < < 5 9 r F.F.F.F.Z.B.v.g.i.4.) p x B B ",
"B b x p ) 4.i.g.v.B.Z.F.F.F.F.f 5 < ; * $ + X . . X + $ * ; < 5 r F.F.F.F.Z.B.v.g.i.4.) p x b B ",
"B b x p E 4.t.g.v.B.Z.F.F.F.F.h 9 < , - % @ O X X O @ $ - , < 9 r F.F.F.F.Z.B.v.g.t.4.E p x b B ",
"b b x p G 4.t.g.v.b.Z.F.F.F.F.x 9 2 , - * $ @ + + @ $ * - , 2 9 r F.F.F.F.Z.b.v.g.t.4.G p x b b ",
"b b x p h 1.w.p.k.b.B.Z.F.F.F.b q 5 < , - * % % $ % * - , < 5 q f F.F.F.Z.Z.b.k.p.w.1.h p x b b ",
"b b x f q >.w.p.k.b.B.Z.F.F.F.B r q 5 < , ; - - * - ; , < 5 q r h F.F.F.Z.B.b.k.p.w.>.q f x b b ",
"  b x f q #.7.i.g.v.b.Z.F.F.F.Z f r 9 5 2 < , , , , < 2 5 9 r f x F.F.F.Z.b.v.g.i.7.#.q f x b   ",
"  x x h r G 4.t.p.k.b.B.Z.F.F.P h f r q 9 5 2 2 2 2 5 9 q r f h b F.F.Z.B.b.k.p.t.4.G r h x x   ",
"  x x h p q >.9.i.g.v.b.Z.Z.F.Y b h f p r q q 9 9 q q r p f h b Z F.Z.Z.B.v.g.i.9.>.q p h x x   ",
"    x h f q [ 4.t.p.k.b.B.Z.F.E B b x h f p p p p p f f h x B Z G F.Z.B.b.k.p.t.4.[ q f h x     ",
"    x h f r r >.9.i.g.v.b.B.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.B.b.v.g.i.9.>.r r f h x     ",
"    x h h p q P 4.w.p.g.v.b.B.Z.Z.F.F.F.F.F.F.F.F.F.F.F.F.F.F.Z.Z.B.b.v.g.p.w.4.P q p h h x     ",
"      h h f r 9 #.7.t.p.k.v.b.B.Z.Z.F.F.F.F.F.F.F.F.F.F.F.F.Z.Z.B.b.v.k.p.t.7.#.9 r f h h       ",
"        h h f r q =.7.t.p.g.v.b.b.B.Z.Z.Z.F.F.F.F.F.F.Z.Z.Z.B.b.b.v.g.p.t.7.=.q r f h h         ",
"        h h f p q p ;.7.t.p.g.k.v.b.b.B.B.Z.Z.Z.Z.Z.Z.B.B.B.b.v.k.g.p.t.7.;.p q p f h h         ",
"          h h f p q p =.7.w.i.p.g.k.v.b.b.b.B.B.B.B.b.b.b.v.k.g.p.i.w.7.=.p q p f h h           ",
"            h h f p q q #.4.9.t.i.p.g.k.k.v.v.v.v.v.v.k.k.g.p.i.t.9.4.#.q q p f h h             ",
"              h h f p q 9 P >.4.9.t.i.p.p.g.g.g.g.g.g.p.p.i.t.9.4.>.P 5 q p f h h               ",
"                h h f p r 9 q ) >.4.7.w.w.t.t.i.i.t.t.w.w.7.4.>.) q 9 r p f h h                 ",
"                  h h f f p r 9 9 G #.>.1.4.4.4.4.4.4.1.>.#.G 9 9 r p f f h h                   ",
"                    h h f f p r r q 5 9 f B Y ~ ~ Y Z f 9 9 q r r p f f h h                     ",
"                        h h f f f p r r q q q 9 9 q q q r r p f f f h h                         ",
"                          f h h f f f f p p p p p p p p f f f f h h f                           ",
"                                h f f f f f f f f f f f f f f h                                 ",
"                                      f f f f f f f f f f                                       "
]
